# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\gloves_test\Program\Ui\sample_list.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_sample_list(object):
    def setupUi(self, sample_list):
        sample_list.setObjectName(_fromUtf8("sample_list"))
        sample_list.resize(1259, 920)
        self.verticalLayout = QtGui.QVBoxLayout(sample_list)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(sample_list)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.checkBox1 = QtGui.QCheckBox(self.groupBox)
        self.checkBox1.setMaximumSize(QtCore.QSize(89, 20))
        self.checkBox1.setChecked(True)
        self.checkBox1.setObjectName(_fromUtf8("checkBox1"))
        self.horizontalLayout_2.addWidget(self.checkBox1)
        self.checkBox2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox2.setMaximumSize(QtCore.QSize(88, 20))
        self.checkBox2.setChecked(True)
        self.checkBox2.setObjectName(_fromUtf8("checkBox2"))
        self.horizontalLayout_2.addWidget(self.checkBox2)
        self.checkBox3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox3.setMaximumSize(QtCore.QSize(88, 20))
        self.checkBox3.setChecked(True)
        self.checkBox3.setObjectName(_fromUtf8("checkBox3"))
        self.horizontalLayout_2.addWidget(self.checkBox3)
        self.verticalLayout.addWidget(self.groupBox)
        self.grPlot = PlotWidget(sample_list)
        self.grPlot.setMaximumSize(QtCore.QSize(16777215, 200))
        self.grPlot.setAutoFillBackground(False)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.grPlot.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.grPlot.setForegroundBrush(brush)
        self.grPlot.setObjectName(_fromUtf8("grPlot"))
        self.verticalLayout.addWidget(self.grPlot)
        self.tableWidget = QtGui.QTableWidget(sample_list)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet(_fromUtf8(" text-align : center;\n"
"   height : 80px;\n"
"   border-style: outset 2px;"))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidget.setRowCount(11)
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 8, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_Privious = QtGui.QPushButton(sample_list)
        self.btn_Privious.setMinimumSize(QtCore.QSize(151, 41))
        self.btn_Privious.setMaximumSize(QtCore.QSize(151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.btn_Privious.setFont(font)
        self.btn_Privious.setObjectName(_fromUtf8("btn_Privious"))
        self.horizontalLayout.addWidget(self.btn_Privious)
        self.btn_Next = QtGui.QPushButton(sample_list)
        self.btn_Next.setMinimumSize(QtCore.QSize(151, 41))
        self.btn_Next.setMaximumSize(QtCore.QSize(151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        self.btn_Next.setFont(font)
        self.btn_Next.setObjectName(_fromUtf8("btn_Next"))
        self.horizontalLayout.addWidget(self.btn_Next)
        self.btn_Export = QtGui.QPushButton(sample_list)
        self.btn_Export.setMaximumSize(QtCore.QSize(151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial Black"))
        font.setBold(True)
        font.setWeight(75)
        self.btn_Export.setFont(font)
        self.btn_Export.setObjectName(_fromUtf8("btn_Export"))
        self.horizontalLayout.addWidget(self.btn_Export)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(sample_list)
        QtCore.QObject.connect(self.btn_Privious, QtCore.SIGNAL(_fromUtf8("clicked()")), sample_list.on_btnPrivStep_clicked)
        QtCore.QObject.connect(self.btn_Privious, QtCore.SIGNAL(_fromUtf8("clicked()")), sample_list.close)
        QtCore.QObject.connect(self.btn_Next, QtCore.SIGNAL(_fromUtf8("clicked()")), sample_list.on_btnNextStep_clicked)
        QtCore.QObject.connect(self.btn_Export, QtCore.SIGNAL(_fromUtf8("clicked()")), sample_list.on_btnExport_clicked)
        QtCore.QMetaObject.connectSlotsByName(sample_list)
        sample_list.setTabOrder(self.tableWidget, self.btn_Privious)

    def retranslateUi(self, sample_list):
        sample_list.setWindowTitle(_translate("sample_list", "Form", None))
        self.label.setText(_translate("sample_list", "                                                                                                                                    Please select specimen for calculating Average Degradation - DR", None))
        self.checkBox1.setText(_translate("sample_list", "specimen1", None))
        self.checkBox2.setText(_translate("sample_list", "specimen2", None))
        self.checkBox3.setText(_translate("sample_list", "specimen3", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("sample_list", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("sample_list", "Color", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("sample_list", "Materia", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("sample_list", "Chemistry", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("sample_list", "Thickness", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("sample_list", "Standard", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("sample_list", "Exposed Time", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("sample_list", "Specimen", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("sample_list", "OPx", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("sample_list", "OPx-Data", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("sample_list", "RPx", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("sample_list", "RPx-Data", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("sample_list", "DRx", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("sample_list", "DR", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.btn_Privious.setText(_translate("sample_list", "Privious Step", None))
        self.btn_Next.setText(_translate("sample_list", "Next Step", None))
        self.btn_Export.setText(_translate("sample_list", "Export Result", None))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    sample_list = QtGui.QWidget()
    ui = Ui_sample_list()
    ui.setupUi(sample_list)
    sample_list.show()
    sys.exit(app.exec_())

