# coding='utf-8'
import os, sys
reload(sys)
sys.setdefaultencoding('utf8')
 
from win32com.client import Dispatch, constants, gencache
 
input_f = 'E:\\WorkSpace\\gloves_test\\Program\\Ui\\11.docx'
output = 'E:\\WorkSpace\\gloves_test\\Program\\Ui\\11.pdf'
 
print 'input file', input
print 'output file', output
# enable python COM support for Word 2007
# this is generated by: makepy.py -i "Microsoft Word 12.0 Object Library"
gencache.EnsureModule('{00020905-0000-0000-C000-000000000046}', 0, 8, 4)
w = Dispatch("Word.Application")
if True:
 print input_f
 doc = w.Documents.Open(input_f, ReadOnly=1)
 doc.ExportAsFixedFormat(output, constants.wdExportFormatPDF, \
       Item=constants.wdExportDocumentWithMarkup,
       CreateBookmarks=constants.wdExportCreateHeadingBookmarks)
try:
    pass
except:
 print ' exception'
finally:
 w.Quit(constants.wdDoNotSaveChanges)
 
if os.path.isfile(output):
 print 'translate success'
else:
 print 'translate fail'
